name: Build release container images
on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      target_stage: fires-server
      push_to_images: |
        ghcr.io/fedimod/fires-server
      # Do not use cache when building releases, so apk update is always ran and the release always contain the latest packages
      cache: false
      # Only tag with latest when ran against the latest stable branch
      # This needs to be updated after each minor version release
      #
      # For multiple versions being supported:
      # latest=${{ startsWith(github.ref, 'refs/tags/v4.3.') }}
      flavor: |
        latest=true
      tags: |
        type=pep440,pattern={{raw}}
        type=pep440,pattern=v{{major}}.{{minor}}
    secrets: inherit
